package cares.restdocskdsl.dsl

import org.springframework.restdocs.snippet.Snippet

/**
 * Holds the snippets generated by [SnippetGenerator] and is used to call the DSL in the [document] function.
 * @see SnippetGenerator
 * @author YoungJun Kim
 */
interface ApiSpec {
    val identifier: String
    val snippets: MutableList<Snippet>
}